version: 2.1
jobs: 
  build:
    docker:
      - image: circleci/node:8
    steps: 
      - checkout 

      - run: yarn install

      - save_cache: 
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch}}
          paths: 
            - ~/.cache/yarn

      - restore_cache: 
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
  test: 
    docker: 
      - image: circleci/node:8
    steps: 
      - checkout 
      - run: echo "hello world"

worflows: 
  version: 2.1
  build_and_test: 
    jobs: 
      - build
      - test


