version: 2.1
jobs: 
  build:
    docker:
      - image: circleci/node:8
    steps: 
      - checkout 

      - run: yarn install

      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - restore_cache: 
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
  test: 
    docker: 
      - image: circleci/node:8
    steps: 
      - checkout 
      - run: echo "hello world"

workflows: 
  version: 2.1
  build_and_test: 
    jobs: 
      - build
      - test


