version: 2.1
jobs: 
  build:
    docker:
      - image: circleci/node:8
    steps: 
      - checkout 

      - restore_cache: 
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - run: yarn install

      - save_cache: 
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch}}
          paths: 
            - ~/.cache/yarn


